# Generated by Django 2.1.4 on 2019-01-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER_MODULE', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={'default_permissions': (), 'permissions': (('add_user', 'add user'), ('change_user', 'update user'), ('delete_user', 'delete user'), ('view_user', 'view user')), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
