# Generated by Django 2.1.4 on 2018-12-31 17:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USER_MODULE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_number', models.CharField(max_length=10, unique=True)),
                ('post', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('USER_MODULE.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registration_number', models.CharField(max_length=8, unique=True)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communications Engineering'), ('IT', 'Information Technology'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CHE', 'Chemical Engineering'), ('PIE', 'Production and Industrial Engineering'), ('BT', 'Biotechnology')], max_length=3)),
                ('year', models.CharField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Final Year')], max_length=1)),
                ('father', models.CharField(blank=True, default='', max_length=70)),
                ('mother', models.CharField(blank=True, default='', max_length=70)),
                ('address', models.CharField(blank=True, default='', max_length=150)),
                ('street', models.CharField(blank=True, default='', max_length=75)),
                ('landmark', models.CharField(blank=True, default='', max_length=75)),
                ('zip', models.CharField(blank=True, default='', max_length=15)),
                ('state', models.CharField(blank=True, default='', max_length=40)),
                ('country', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('USER_MODULE.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
